# AutoML using TPOT
Databae: <br>
 - IRIS dataset<br>


##### **Package to install** 
 - pip install tpot


In [ ]:
# Load libraries

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

import pandas as pd 
import numpy as np

In [ ]:
# Data sources
data1 = "https://raw.githubusercontent.com/sanketpadwal/GCDAI_INSAID_JAN20/main/Misc/TPOT/Iris.csv"
data2 = ""

In [ ]:
# Load data
df1 = pd.read_csv(data1)

In [ ]:
df1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df1.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df1.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
# unique class values
df1['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
# Label target class categorical to numerical

ref = {value:index for index,value in enumerate(df1['Species'].unique())}

In [ ]:
ref

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

In [ ]:
# Create new target label in numerical format
df1['Iris_label'] = df1['Species'].map(ref)

In [ ]:
df1.head()

Id  SepalLengthCm  SepalWidthCm  ...  PetalWidthCm      Species Iris_label
0   1            5.1           3.5  ...           0.2  Iris-setosa          0
1   2            4.9           3.0  ...           0.2  Iris-setosa          0
2   3            4.7           3.2  ...           0.2  Iris-setosa          0
3   4            4.6           3.1  ...           0.2  Iris-setosa          0
4   5            5.0           3.6  ...           0.2  Iris-setosa          0

[5 rows x 7 columns]

In [ ]:
x = df1[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df1['Iris_label']

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cv_scores = cross_val_score(LogisticRegression(),x,y,cv=10)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [ ]:
cv_scores

array([1.        , 0.93333333, 1.        , 1.        , 0.93333333,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [ ]:
print(np.mean(cv_scores))

0.9733333333333334


In [ ]:
# Individual Algorithm
rf_cv_scores = cross_val_score(RandomForestClassifier(),x,y,cv=10)

In [ ]:
rf_cv_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [ ]:
print(np.mean(rf_cv_scores))

0.9666666666666666


In [ ]:
# Individual Algorithm
rf_cv_scores2 = cross_val_score(RandomForestClassifier(n_estimators=100,max_depth=2),x,y,cv=10)

In [ ]:
rf_cv_scores2

array([0.93333333, 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

In [ ]:
print(np.mean(rf_cv_scores2))

0.9533333333333334


# AutoML with TPOT

In [ ]:
# Install TPOT libraries
!pip install -q tpot

In [ ]:
# import tpot library
import tpot

In [ ]:
# Methods and Attributes
dir(tpot)

['TPOTClassifier',
 'TPOTRegressor',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_version',
 'base',
 'builtins',
 'config',
 'decorators',
 'driver',
 'export_utils',
 'gp_deap',
 'gp_types',
 'main',
 'metrics',
 'operator_utils',
 'tpot']

In [ ]:
# Split in train and test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
# Init
tpot = TPOTClassifier(generations=5,verbosity=2)

In [ ]:
# Fit data
tpot.fit(x_train,y_train)


Generation 1 - Current best internal CV score: 0.9714285714285715

Generation 2 - Current best internal CV score: 0.9714285714285715

Generation 3 - Current best internal CV score: 0.9714285714285715

Generation 4 - Current best internal CV score: 0.9714285714285715

Generation 5 - Current best internal CV score: 0.9714285714285715

Best pipeline: MLPClassifier(input_matrix, alpha=0.1, learning_rate_init=0.001)


TPOTClassifier(config_dict=None, crossover_rate=0.1, cv=5,
               disable_update_check=False, early_stop=None, generations=5,
               log_file=None, max_eval_time_mins=5, max_time_mins=None,
               memory=None, mutation_rate=0.9, n_jobs=1, offspring_size=None,
               periodic_checkpoint_folder=None, population_size=100,
               random_state=None, scoring=None, subsample=1.0, template=None,
               use_dask=False, verbosity=2, warm_start=False)

In [ ]:
tpot.score(x_test,y_test)

1.0

In [ ]:
# Export the result
tpot.export('tpot_ml_pipeline.py')

In [ ]:
# Predictions
ex = np.array([6.2,3.4,5.4,2.3]).reshape(1,-1)

In [ ]:
tpot.predict(ex)

array([2])

In [ ]:
ref

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}